### ISSUE TITLE
没有支付时的paySign生成

### ISSUE THREAD

**Issue by kalooboy** [sigoden/wechatpay#5]
我们自己维护的库里面是这个放在服务端生成的,因为涉及到了key,这个如果放在前端被找到很危险,不知道这个库没有做这个paySign的方法是出于什么考虑呢?

**Comment by sigoden** [comment]
如果你指的签名函数，有的，见 [uitils.ts:sign](https://github.com/sigoden/wechatpay/blob/1e0c0eb651dacc52ae70a7e0ad1e58f698f0d643/src/utils.ts#L55)
