### ISSUE TITLE
setDebug不成功

### ISSUE THREAD

**Issue by lixiang02** [sigoden/wechatpay#7]
setDebug 需要请求获取key链接应该是https://api.mch.weixin.qq.com/sandboxnew/pay/getsignkey吧 但是源代码中确是https://api.mch.weixin.qq.com/pay/getsignkey， 报了404，问一下作者这个是什么情况

**Comment by keminshu** [comment]
实际上小程序支付暂时还没有沙箱支付环境，也没有对应的验收测试case，很尴尬。
